### ISSUE TITLE
Python backend error on import requests

### ISSUE THREAD

**Issue by 42-dd** [cbdevnet/midimonster#87]
Hi.
Thanks for your work on midimonster.
Sadly I#ve run into another issue with the python backend:

I tried to send request.get from python after receiving rtpMidi.

I get the following error on starting midimonster:

> Traceback (most recent call last):
  File "/etc/midimonster/mymodule.py", line 3, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 28, in <module>
    from six.moves import queue
  File "/usr/lib/python3/dist-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/lib/python3/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.7/queue.py", line 16, in <module>
    from _queue import Empty
ImportError: /usr/lib/python3.7/lib-dynload/_queue.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: PyExc_MemoryError

This happens as soon as I pu `import requests` into my python script.
Script and config (just examples are attached).

Any way to fix this error?

Thanks in advance.

![Bildschirmfoto 2021-03-19 um 13 52 03](https://user-images.githubusercontent.com/71632233/111783407-7d27ff80-88ba-11eb-81ef-333b222b0f4a.png)

[files.zip](https://github.com/cbdevnet/midimonster/files/6171234/files.zip)

**Comment by cbdevnet** [comment]
Hi @42-dd, thanks for the Report! We're currently experiencing issues with the Python backend (see also #83). I can't currently give a good timeline for this being fixed as I'm a bit short on time at the moment.

I will update you here once I have news :)
